---

- hosts: all
  become: true
  pre_tasks:

  - name: nagios installation (Ubuntu)
    apt: 
      name:
        - nagios4
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: nagios installation (CentOS)
    dnf:
       name:
         - nagios
       state: latest
       update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:

  - name: Banner Motd (Ubuntu)
    debug:
      msg: "Ansible Managed by Leonen"
    when: ansible_distribution == "Ubuntu"

  - name: Banner Motd (CentOS)
    debug:
      msg: "Ansible Managed by Leonen"
    when: ansible_distribution == "CentOS"
